import Background from "@/components/Background";
import MainBox from "@/components/MainBox";
import { Container } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3 test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxW={1920}
        w="full"
        h="100vh"
        position="relative"
        overflowX="hidden"
      >
        <Background />
        <MainBox />
      </Container>
    </>
  );
}
